service: api-gateway-api-key-example

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: ${opt:stage, self:custom.defaultStage}
  apiKeys:
    - ${self:provider.stage}-api-gateway-api-key-example

plugins:  
  - serverless-webpack

custom:
  defaultStage: dev

functions:
  hello:
    handler: handler.hello
    events:
        - http:
            path: hello
            method: get
            private: true
